### ISSUE TITLE
is this still supported? If yes didnt get any output of Multicounter

### ISSUE THREAD

**Issue by JanWeskampJTL** [Talon24/slabs-chatbot-scripts#6]
is this still supported? If yes didnt get any output of Multicounter

**Comment by Talon24** [comment]
Hello @JanWeskamp 
Thanks for the report and the patience.
It used to be that the streamer had to list themself as a trusted user, but now that shouldn't be necessary anymore. Let me know if that didn't fix the issue.

**Comment by JanWeskampJTL** [comment]
Thanks seems to work perfectly right now
